export enum ACTION {
  GOOGLE_AUTH = 'google-auth',
  GOOGLE_ONE_TAP_AUTH = 'google-one-tap-auth',
  GOOGLE_AUTH_UNLINK = 'google-auth-unlink',
  GOOGLE_LOGIN = 'google-login',
  CONNECT_GOOGLE_ACCOUNT = 'connect-google-account',
  VERIFY_GOOGLE_TOKEN = 'google-verify-token',
  APPLE_AUTH = 'apple-auth',
  APPLE_LOGIN = 'apple-login',
  APPLE_AUTH_UNLINK = 'apple-auth-unlink',
  VERIFY_APPLE_TOKEN = 'apple-verify-token',
  CONNECT_APPLE_ACCOUNT = 'connect-apple-account',
  REGISTER = 'register',
  LOGIN = 'login',
  LOGOUT = 'logout',
  UPDATE_EMAIL = 'update-email',
  CONFIRM_EMAIL = 'confirm-email',
  CHANGE_PASSWORD = 'change-password',
  CONFIRM_PASSWORD = 'confirm-password',
  VERIFY_TOKEN = 'verify-token',
  SWITCH_CONTEXT = 'switch-context',
  RETRIEVE_BY_LOOKUP_KEY = 'retrieve-by-lookup-key',
  RETRIEVE_BY_PRIVILEGE = 'retrieve-by-privilege',
  CREATE_PRIVILEGE = 'create-privilege',
  UPDATE_PRIVILEGE = 'update-privilege',
  UPSERT_PRIVILEGES = 'upsert-privileges',
  DELETE_PRIVILEGE = 'delete-privilege',
  DELETE_PRIVILEGES = 'delete-privileges',
  REMOVE_PRIVILEGES_BY_RESOURCE = 'remove-privileges-by-resource',
  REMOVE_PRIVILEGES_BY_RESOURCE_AND_ROLE = 'remove-privileges-by-resource-and-role',
  CHECK_EXISTENCE = 'check-existence',
  RETRIEVE_CONNECTED_ACCOUNTS = 'retrieve-connected-accounts',
  VERIFY_USER = 'verify-user',
  VERIFY_SECONDARY_EMAIL = 'verify-secondary-email',
  FORGOT_PASSWORD = 'forgot-password',
  RESET_PASSWORD = 'reset-password',
  RESEND_VERIFICATION = 'resend-verification',
  PROFILE_ME = 'profile-me',
  UNBLOCK_USER = 'unblock-user',
  ADD_SECONDARY_EMAIL = 'add-secondary-email',
  REMOVE_SECONDARY_EMAIL = 'remove-secondary-email',
  RETRIEVE_PROFILE_VIEW_MAP = 'retrieve-profile-view-map',

  CREATE = 'create',
  CREATE_MANY = 'create-many',
  RETRIEVE = 'retrieve',
  RETRIEVE_LATEST = 'retrieve-latest',
  RETRIEVE_MANY = 'retrieve-many',
  RETRIEVE_VERSION = 'retrieve-version',
  RETRIEVE_VERSIONS = 'retrieve-versions',
  RETRIEVE_SOCIAL_LINKS = 'retrieve-social-links',
  SMALL_RETRIEVE = 'small-retrieve',
  BULK_RETRIEVE = 'bulk-retrieve',
  SIGNED_URL_RETRIEVE = 'signed-url-retrieve',
  UPDATE = 'update',
  UPDATE_MANY = 'update-many',
  DELETE = 'delete',
  DELETE_MANY = 'delete-many',
  SEARCH = 'search',
  SEARCH_PROFILES_AND_ORGANIZATIONS = 'search-profiles-and-organizations',
  SEARCH_STAKEHOLDERS = 'search-stakeholders',
  SEARCH_CONNECT_CUSTOMERS = 'search-connect-customers',
  GLOBAL_SEARCH = 'global-search',
  MOST_RECENT = 'most-recent',
  LIST_ALL = 'list-all',
  LIST_NON_PAGINATED = 'list-non-paginated',
  LIST_ALL_POPULATED_CHAPTERS = 'list-all-populated-chapters',
  LIST_ALL_SOCIAL_LINKS = 'list-all-social-links',
  LIST_FROM_DATE = 'list-from-date',
  LIST_ALL_LECTURES_FROM_COURSES = 'list-all-lectures-from-courses',
  LIST_ALL_LECTURES_FROM_SUBJECT = 'list-all-lectures-from-subjects',
  LIST_ALL_SUB_CATEGORIES = 'list-all-subcategories',
  DELETE_ALL = 'delete-all',
  DELETE_AND_RETRIEVE = 'delete-and-retrieve',
  LIST_ALL_LATEST = 'list-all-latest',
  VALIDATE = 'validate',
  CREATE_MANY_MEMBERS = 'create-many-members',
  ASSIGN_CATEGORIES_WITH_AI = 'assign-categories-with-ai',
  UNASSIGN = 'unassign',
  UNASSIGN_MANY = 'unassign-many',
  ASSIGN_MANY = 'assign-many',
  LIST_ALL_SECONDARY_EMAILS = 'list-all-secondary-emails',
  LIST_BLOCKED_USERS = 'list-blocked-users',
  SEARCH_VERIFYING_COURSES = 'search-verifying-courses',
  LIST_VERIFYING_COURSES = 'list-verifying-courses',

  RESTORE = 'restore',
  CLONE = 'clone',
  USER_ATTENDED = 'user-attended',
  RETRIEVE_MEMBERS = 'retrieve-members',

  RETRIEVE_BY_ENTITY = 'retrieve-by-entity',
  RETRIEVE_FROM_EVENT = 'retrieve-from-event',

  UPDATE_SCHEDULE = 'update-schedule',

  USER_RETRIEVE = 'user-retrieve',
  RETRIEVE_SIGNED_URL = 'retrieve-signed-url',
  RETRIEVE_SIGNED_URLS = 'retrieve-signed-urls',
  METADATA_RETRIEVE = 'metadata-retrieve',
  RETRIEVE_SIZE = 'retrieve-size',
  CREATE_ENTITY_BUCKET = 'create-entity-bucket',
  RETRIEVE_ENTITY_BUCKET = 'retrieve-entity-bucket',

  INIT = 'init',
  UPLOAD = 'upload',
  SIGNED_UPLOAD = 'signed-upload',
  SIGNED_UPLOADS = 'signed-uploads',
  LIST_FILES = 'list-files',
  TRANSFER_FILE_FROM_URL = 'transfer-file-from-url',
  CREATE_FILE_FROM_JOB = 'create-file-from-job',

  REORDER = 'reorder',
  JUMP = 'jump',

  MUTE = 'mute',
  UNREAD = 'unread',
  READ = 'read',
  READ_ALL = 'read-all',
  UPDATE_ROLE = 'update-role',
  PIN = 'pin',
  CLEAR_HISTORY = 'clear-history',
  RETRIEVE_ACTUAL_ROOM = 'retrieve-actual-room',

  ADD_ITEM = 'add-item',
  UPDATE_ITEM = 'update-item',
  DELETE_ITEM = 'delete-item',

  ADD_PAYMENT_METHOD = 'add-payment-method',
  DELETE_PAYMENT_METHOD = 'delete-payment-method',
  SET_DEFAULT_PAYMENT_METHOD = 'set-default-payment-method',
  CHECKOUT = 'checkout',
  CREATE_ORGANIZATION_CONNECT = 'create-organization-connect',
  CREATE_PROFILE_CONNECT = 'create-profile-connect',
  CREATE_ACCOUNT_LINK = 'create-account-link',
  CREATE_ACCOUNT_BALANCE_SESSION = 'create-account-balance-session',
  GET_COUNTRY_LIST = 'get-country-list',
  GET_BILLING_INFO = 'get-billing-info',
  RETRIEVE_CONNECT_BALANCE = 'retrieve-connect-balance',
  UPDATE_PAYOUT_SCHEDULE = 'update-payout-schedule',
  CREATE_SETUP_INTENT = 'create-setup-intent',
  LIST_UPCOMING_BILLINGS = 'list-upcoming-billings',
  LIST_ALL_FUTURE_PAYMENTS = 'list-all-future-payments',
  RETRIEVE_DEFAULT = 'retrieve-default',
  RETRY_PAYMENT = 'retry-payment',
  CHECK_SUBSCRIPTION_ACCESS = 'check-subscription-access',
  CREATE_SERVICE_SUBSCRIPTION = 'create-service-subscription',

  GET_PROFILE_SPACES = 'get-profile-spaces',
  RETRIEVE_UNIQUE_TRANSACTIONS_BY_BUYER = 'retrieve-unique-transactions-by-buyer',
  RETRIEVE_UNIQUE_TRANSACTIONS_BY_RECIPIENT = 'retrieve-unique-transactions-by-recipient',
  RETRIEVE_UNIQUE_TRANSACTIONS_BY_COURSE = 'retrieve-unique-transactions-by-course',

  HANDLE_ACCOUNT_UPDATED = 'handle-account-updated',
  HANDLE_PERSON_UPDATED = 'handle-person-updated',
  HANDLE_CHARGE_UPDATED = 'handle-charge-updated',
  HANDLE_EXTERNAL_ACCOUNT_CREATED = 'handle-external-account-created',
  HANDLE_EXTERNAL_ACCOUNT_UPDATED = 'handle-external-account-updated',
  HANDLE_VERIFICATION_SESSION_UPDATED = 'handle-verification-session-updated',
  HANDLE_SUBSCRIPTION_CREATED = 'handle-subscription-created',
  HANDLE_INVOICE_PAYMENT_SUCCEEDED = 'handle-invoice-payment-succeeded',
  HANDLE_INVOICE_PAYMENT_FAILED = 'handle-invoice-payment-failed',
  HANDLE_PAYOUT_CREATED = 'handle-payout-created',
  HANDLE_PAYOUT_PAID = 'handle-payout-paid',
  HANDLE_PAYOUT_FAILED = 'handle-payout-failed',
  HANDLE_PAYOUT_CANCELED = 'handle-payout-canceled',
  HANDLE_SUBSCRIPTION_DELETED = 'handle-subscription-deleted',

  LIST_USER_ROOMS = 'list-user-rooms',
  UPDATE_ROOM_MEMBER = 'update-room-member',
  LIST_ALL_LINKS = 'list-all-links',
  SEARCH_LINKS = 'search-links',
  FORWARD_MESSAGE = 'forward-message',
  READ_MESSAGE = 'read-message',
  HISTORY = 'history',
  RETRIEVE_COMMON_ROOMS = 'retrieve-common-rooms',

  INVITE = 'invite',
  LIST_ALL_INVITES = 'list-all-invites',
  CHECK_INVITE_STATUS = 'check-invite-status',
  GET_INVITE_LINK = 'get-invite-link',
  BULK_DELETE = 'bulk-delete',
  UPDATE_REVIEW = 'update-review',
  COUNT_REVIEWS = 'count-reviews',

  ACCEPT_INVITATION = 'accept-invitation',
  DECLINE_INVITATION = 'decline-invitation',
  DELETE_INVITATION = 'delete-invitation',

  RETRIEVE_OWNERS = 'retrieve-owners',

  START_LIVE_STREAM = 'start-live-stream',
  GET_LIVE_STREAM_URL = 'get-live-stream-url',
  STOP_LIVE_STREAM = 'stop-live-stream',
  GET_AUTH_TOKEN = 'get-auth-token',
  TOGGLE_ROOM_STATUS = 'toggle-room-status',
  GET_RECORDING = 'get-recording',
  GET_RECORDING_ASSET = 'get-recording-assets',
  HANDLE_EVENT_CALLBACK = 'handle-event-callback',
  GET_EVENT_MEETING_TOKEN = 'get-event-meeting-token',
  GET_ROOM_MEETING_TOKEN = 'get-room-meeting-token',

  PUBLISH = 'publish',
  REVIEW = 'review',

  MARK_AS_BEST_ANSWER = 'mark-as-best-answer',

  LIST_MEMBERS = 'list-members',

  OWNER_OR_MEMBER = 'owner_or_member',

  FILTER_MEMBERS = 'filter-members',
  RETRIEVE_LECTURE_CONTEXT = 'retrieve-lecture-context',

  ASSIGN_LICENSE = 'assign-license',
  REMOVE_LICENSE = 'remove-license',
  MOVE_LICENSES = 'move-licenses',
  GET_LICENSED_MEMBERS = 'get-licensed-members',

  GENERATE = 'generate',

  RETRIEVE_TIMELINE = 'retrieve-timeline',
  RETRIEVE_SPENDING = 'retrieve-spending',
  RETRIEVE_INCOME = 'retrieve-income',
  RETRIEVE_LAST_INCOME = 'retrieve-last-income',

  RETRIEVE_ACTIVITY = 'retrieve-activity',
  RETRIEVE_SOLVING_RATE = 'retrieve-solving-rate',
  RETRIEVE_ANSWERED_BY_ME = 'retrieve-answered-by-me',

  RETRIEVE_RANKING = 'retrieve-ranking',
  RETRIEVE_RATING = 'retrieve-rating',

  RETRIEVE_OVERVIEW = 'retrieve-overview',

  MODERATE_CONTENT = 'moderate-content',
  COUNT_UNREAD = 'count-unread',
  RETRIEVE_PRIVATE_EVENTS = 'retrieve-private-events',
  AVAILABLE_CALENDARS = 'available-calendars',
  RETRIEVE_MANY_CALENDARS = 'retrieve-many-calendars',
  LIST_AVAILABLE_CALENDARS = 'list-available-calendars',
  LIST_NOTIFICATION_SENDERS = 'list-notification-senders',
  LIST_ALL_PROFILE_VIEWER = 'list-all-profile-viewer',
  ALL_USER_COURSES = 'all-user-courses',
  RETRIEVE_USER_EVENTS_WITHIN_DATES = 'retrieve-user-events-within-dates',
  MOVE_COURSES = 'move-courses',

  UPDATE_POST_NOTIFICATION = 'update-post-notification',
  UPDATE_SOCIAL_NOTIFICATION = 'update-social-notification',
  ADD_SELECTED_CALENDARS = 'add-selected-calendar',
  RETRIEVE_SELECTED_CALENDARS = 'retrieve-selected-calendar',
  REMOVE_SELECTED_CALENDARS = 'remove-selected-calendar',
  PREVIEW = 'preview',
  LIST_CONNECT_CUSTOMERS = 'list-connect-customers',
  LIST_ALL_CUSTOMER_TRANSACTIONS = 'list-all-customer-transactions',
  LIST_ALL_PURCHASED_PRODUCTS = 'list-all-purchased-products',
  PROCESS_INVOICE_FILES = 'process-invoice-files',
  UPDATE_PREFERENCES = 'update-preferences',
  TEST_WEBHOOK = 'test-webhook',
  TEST_NEW_WEBHOOK = 'test-new-webhook',
  LIST_ALL_EVENT_CATEGORIES = 'list-all-event-categories',
  LIST_ALL_GROUPED = 'list-all-grouped',
  SEARCH_GROUPED = 'search-grouped',
  LEAVE = 'leave',
  RENDER = 'render',
  RETRIEVE_PROFILE_AND_ORGANIZATION = 'retrieve-profile-and-organization',
  GET_PROFILES_AND_GROUPS = 'get-profiles-and-groups',

  GET_INVITATION = 'get-invitation',
  CREATE_FCM_TOKEN = 'create-fcm-token',
  DELETE_FCM_TOKEN = 'delete-fcm-token',
  UPDATE_GROUPS_ROLES = 'update-groups-roles',
  RETRIEVE_BY_OWNER = 'retrieve-by-owner',

  SEND_EVENT = 'send-event',
  RETRIEVE_ORGANIZATION_CUSTOMER = 'retrieve-organization-customer',
  UPDATE_COUNTRY = 'update-country',
  CHECK_STRIPE_SIGNATURE = 'check-stripe-signature',

  SEARCH_BRANDS = 'search-brands',
  RETRIEVE_BY_EMAIL = 'retrieve-by-email',
  LIST_ALL_BY_COURSE_ID = 'list-all-by-course-id',
  LIST_ALL_COMMON_EVENTS = 'list-all-profile-common-events',
  CREATE_CYCLE = 'create-cycle',
  SWITCH_CYCLE = 'switch-cycle',
  DELETE_CYCLE = 'delete-cycle',
  VISBILITY_CHANGED_TO_PRIVATE = 'visibility-changed-to-private',

  LIST_ALL_GROUPS = 'list-all-groups',

  LIST_ROLES = 'list-roles',
  DELETE_FOLDER = 'delete-folder',

  REMOVE_SPACE_MEMBER = 'remove-space-member',
  COURSE_PUBHLISHED = 'course-published',
  REMOVE_CALENDER_MEMBER = 'remove-calender-member',
  SELECTED_CALENDER = 'selected-calender',
  CREATE_AI_BILLING = 'create-ai-billing',
  CREATE_SITE = 'create-site',
  REMOVE_SITE = 'remove-site',
  GET_CYCLE = 'get-cycle',
  GET_COURSE_CYCLE_MAP = 'get-user-cycles',
  RETRIEVE_LECTURE_EVENTS = 'retrieve-lecture-events',
  CREATE_BUCKET_WITH_FILE_TRANSFER = 'create-bucket-with-file-trasfer',
  HIDE = 'hide',

  SUGGEST_SUB_CATEGORIES = 'suggest-sub-categories',
  UPDATE_ASSISTANT = 'update-assistant',
}
