export const CONFIG_TOKEN = {
  APP: 'app',
  CACHE: 'cache',
  DATABASE: 'database',
  GOOGLE_AUTH: 'googleAuth',
  HMS: 'hms',
  IAM: 'iam',
  MICROSERVICES: 'microservices',
  REDIS: 'redis',
  SCYLLADB: 'scylladb',
  SERVER: 'server',
  SOCKET: 'socket',
  STRIPE: 'stripe',
  GC: 'gc',
  AI: 'ai',
  ANALYTICS: 'analytics',
  CONTENT_MODERATION: 'content-moderation',
  SYSTEM_USER: 'system-user',
  PRODUCT_PRICE: 'product-price',
  CLOUDINARY: 'cloudinary',
};
